import * as sdk from 'node-appwrite'

const APPWRITE_CLOUD_URL: string = process.env.APPWRITE_CLOUD_URL as string;
const APPWRITE_PROJECT_ID: string = process.env.APPWRITE_PROJECT_ID as string;
const APPWRITE_APP_KEY: string = process.env.APPWRITE_APP_KEY as string;

const client = new sdk.Client()
	.setEndpoint(APPWRITE_CLOUD_URL)
	.setProject(APPWRITE_PROJECT_ID)
	.setKey(APPWRITE_APP_KEY);

const storage = new sdk.Storage(client);
const databases = new sdk.Databases(client);

// Constants
const DATABASE_ID = process.env.DATABASE_ID || "";
const BOOKS_COLLECTION_ID = process.env.BOOKS_COLLECTION_ID || "";
const CHUNKS_COLLECTION_ID = process.env.CHUNKS_COLLECTION_ID || "";
const BLOGS_COLLECTION_ID = process.env.BLOGS_COLLECTION_ID || "";
const PUBLICLY_SHARED_BLOGS_COLLECTION_ID = process.env.PUBLICLY_SHARED_BLOGS_COLLECTION_ID || "";
const CONTENT_DELETION_COLLECTION_ID = process.env.CONTENT_DELETION_COLLECTION_ID || "";
const BUCKET_ID = process.env.BUCKET_ID || "";
const SUBSCRIPTIONS_COLLECTION_ID = process.env.SUBSCRIPTIONS_COLLECTION_ID || "";
const TOKENISATION_COLLECTION_ID = process.env.TOKENISATION_COLLECTION_ID || "";
const INITIATED_TRANSACTIONS_COLLECTION_ID = process.env.INITIATED_TRANSACTIONS_COLLECTION_ID || '';
const SUBSCRIPTION_QUOTA_COLLECTION_ID = process.env.SUBSCRIPTION_QUOTA_COLLECTION_ID || '';
const PURPLE_FEEDBACKS_COLLECTION_ID = process.env.PURPLE_FEEDBACKS_COLLECTION_ID || '';
const CATEGORY_COLLECTION_ID = process.env.CATEGORY_COLLECTION_ID || '';
const FREE_CONTENT_GENERATION_ENTRIES = process.env.FREE_CONTENT_GENERATION_ENTRIES || '';
const IMAGES_WITH_METADATA_COLLECTION_ID = process.env.IMAGES_WITH_METADATA_COLLECTION_ID || '';

export  {
	APPWRITE_CLOUD_URL,
	APPWRITE_PROJECT_ID,
	APPWRITE_APP_KEY,
	TOKENISATION_COLLECTION_ID,
	PUBLICLY_SHARED_BLOGS_COLLECTION_ID,
	INITIATED_TRANSACTIONS_COLLECTION_ID,
	SUBSCRIPTION_QUOTA_COLLECTION_ID,
	IMAGES_WITH_METADATA_COLLECTION_ID,
	SUBSCRIPTIONS_COLLECTION_ID,
	FREE_CONTENT_GENERATION_ENTRIES,
	storage,
	databases,
	DATABASE_ID,
	BOOKS_COLLECTION_ID,
	CHUNKS_COLLECTION_ID,
	BLOGS_COLLECTION_ID,
	CONTENT_DELETION_COLLECTION_ID,
	PURPLE_FEEDBACKS_COLLECTION_ID,
	CATEGORY_COLLECTION_ID,
	BUCKET_ID,
}
